spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1692
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 245304631780-6asm7t7klcdsn6652cssndt8g63a0gma.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          naver:
            client-id: UjWPU2O7JqyBfjCTbuoe
            client-secret: H1fZaupgkM
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate.sql: debug
